Fix/web cli export
cleanlab/cleanlab-studio pull request #121
Opened 2023-08-01 00:52 UTC by kat-wicks

Based on conversations with @ulya-tkch  and @anishathalye, we are updating the CLI, Python library, and Web export to have the same columns to reduce confusion.

Instead of somewhat strange "only ID + corrected label"/"all cleanlab columns"/"all cleanlab columns except action" export options, now have "only ID + corrected"/"all cleanlab columns"/"all project-related columns" for CLI/python export, which can be mixed and matched. This gives more information to CLI users , who previously were missing project information like actions taken, if a datapoint was initially unlabeled, etc. the "--all" flag is preserved.

2023-08-02 21:42 UTC, clu0 requested changes
Code looks good to me, but if we are exporting some new columns (like "initially unlabeled", from looking at the backend code), we should add documentation for them in the concepts section

2023-08-07 20:19 UTC, kat-wicks commented
** test with Pyspark

2023-08-17 21:08 UTC, clu0 commented on docs/source/concepts/cl_columns.rst
> +| Previously Resolved           | :ref:`previously_resolved <previously_resolved>`  | Boolean      |
let's change all the names for booleans to `is_...`

2023-08-17 21:08 UTC, clu0 commented on docs/source/concepts/cl_columns.rst
> +| Initially Unlabeled           | :ref:`initially_unlabeled <initially_unlabeled>`  | Boolean      |
change to `is_`

2023-08-17 21:11 UTC, clu0 commented on docs/source/concepts/cl_columns.rst
> +Project Information Columns
I don't think it makes sense to have the `Project Information Columns` be a subsection under the Cleanlab Columns page.

I think better to add a new page Project Information Columns, and link it directly under the "Concepts" page

2023-08-17 21:14 UTC, clu0 commented on docs/source/concepts/cl_columns.rst
> +You can also retrieve information/metadata related to the Cleanlab project itself.
I think this line would be better if it were more descriptive. Maybe something like this?

For each project that you run in Cleanlab Studio, Cleanlab stores a number of metadata columns that can be retrieved using the Python API. Currently we store the following project information columns:

2023-08-20 01:04 UTC, clu0 commented on docs/source/concepts/project_information.rst
> +To get this information, use ``studio.download_cleanlab_columns()`` and add the argument -p or -a for project details or all columns including analysis columns respectively.
wait I don't understand what this line means. What is the argument you're supposed to pass into the `download_cleanlab_columns` function when you use the python CLI to get the project info columns?

2023-08-20 01:09 UTC, clu0 requested changes
tests against dev still buggy

2023-08-21 18:29 UTC, clu0 approved these changes
seems to work now, lgtm

2023-08-23 19:06 UTC, merged