[TLM API] Add new api features to user facing api
cleanlab/cleanlab-studio pull request #154
Opened 2023-12-07 01:25 UTC by ulya-tkch

- should we mention default values here (since they are default internally but might be good to know but look confusing in the function?)

2023-12-07 04:06 UTC, jwmueller commented on cleanlab_studio/studio/trustworthy_language_model.py
> +    Parameters
where are we mentioning that quality-presets determine many of these settings, but specifying them here will over-ride the setting from the quality-preset ?

2023-12-25 21:52 UTC, ryansingman requested changes

2023-12-25 21:52 UTC, ryansingman commented on cleanlab_studio/studio/trustworthy_language_model.py
> +    use_self_reflection: bool
need to mark these as not required

https://peps.python.org/pep-0655/#usage-in-python-3-11

2024-02-14 16:37 UTC, ryansingman approved these changes
need to wait to merge/release for the backend changes to be deployed. LGTM

2024-02-19 17:55 UTC, merged