Feature: improved schema proposition error handling
cleanlab/cleanlab-studio pull request #72
Opened 2022-12-26 20:02 UTC by ryansingman

2022-12-26 20:08 UTC, ryansingman commented
Merge order:
- [CLI](https://github.com/cleanlab/cleanlab-studio/pull/72)- [Frontend](https://github.com/cleanlab/cleanlab-studio-frontend/pull/240)
- [Backend](https://github.com/cleanlab/cleanlab-studio-backend/pull/183)

2022-12-27 18:42 UTC, anishathalye requested changes
I like the principle of giving more specific error messages in general, though I wouldn't work too hard to support particularly badly formatted datasets like empty ones.

This change seems fine overall, aside from some minor details.

2022-12-27 18:42 UTC, anishathalye commented on cleanlab_studio/errors.py
> +    ...
I think it's idiomatic to use `pass` rather than Ellipsis here

2022-12-27 18:42 UTC, anishathalye commented on cleanlab_studio/version.py
> +__version__ = "0.1.20"
Let's do version bumps separately

2022-12-27 18:42 UTC, anishathalye commented on cleanlab_studio/errors.py
> +class InvalidDatasetError(RuntimeError):
Subclass `ValueError` instead? It's more specific and makes sense in this context.

2022-12-27 20:41 UTC, ryansingman commented
> I like the principle of giving more specific error messages in general, though I wouldn't work too hard to support particularly badly formatted datasets like empty ones.
> 
> This change seems fine overall, aside from some minor details.

Agreed on not wanting to support egregiously badly formatted datasets. This change is just to allow us to catch and handle those errors properly (not resulting in unhandled exceptions in the backend)

2022-12-28 15:15 UTC, anishathalye approved these changes

2022-12-28 18:47 UTC, merged